name = "vars"
version = "1.0.0"

# HTMLドキュメントを生成したり、Hexパッケージマネージャーに
# プロジェクトを公開したりする場合は、以下のフィールドを入力してください。
#
# description = ""
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "", repo = "" }
# links = [{ title = "Website", href = "" }]
#
# 利用可能なすべてのオプションの詳細については、
# https://gleam.run/writing-gleam/gleam-toml/ を参照してください。

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
envoy = ">= 1.0.2 and < 2.0.0"
argv = ">= 1.0.2 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
